### ISSUE TITLE
Error while running running the script

### ISSUE THREAD

**Issue by varunamrutiya** [fisadev/conky-draw#1]
When i run the code as per specified by the guidelines i get the following error in the terminal.
"**Conky: llua_do_call: function conky_main execution failed: ./conky_draw.lua:312: attempt to concatenate field 'kind' (a nil value)**"

I think the error is at line 312. Pls have look.

My config_draw_config.lua has followind content

`elements = {
kind = 'bar_graph',
conky_value = 'wireless_link_qual wlan0',
from = {x=50,y=200},
to = {x=100,y=200},
background_thickness = 5,
background_color = 0xFFFFFF,
bar_thickness = 5,
critical_threshold = 80,
change_color_on_critical = true,
bar_color_on_critical = 0x5dc643
}`

My lua bindings in conky are working properly i already checked it.

**Comment by fisadev** [comment]
Hi!
The variable elements must be a list of elements, not a single element:

You did:

```
elements = {element attrs.}
```

You should do

```
elements = {{element attrs}}
```

Because it's a list, to be able to define many elements like this:

```
elements = {{element attrs}, {another element attrs}, ...}
```

**Comment by varunamrutiya** [comment]
Yes, found the error. Thnx :D
