### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by Daguhh** [fisadev/conky-draw#5]
Hi,

thanks for your great work, that's exactly what I was looking for,
but... yes, there is a but... So but I find it quite hard to navigate through the config file when you have tons of objects.
So I tried to make a python GUI to generate the config_draw.lua file,
It's still in progress, not very strong, but It's kinda working
please have a look on https://github.com/Daguhh/ConkyLuaMakerGUIv2,
there is a preview of GUI and the conky running

**Comment by fisadev** [comment]
Nice!! Thanks for the work on the GUI, is very useful. I'll add a link in this repo :)

**Comment by fisadev** [comment]
Done! link added in the readme :)
